####################################################################################################
#
# BookBrowser - A Digitised Book Solution
# Copyright (C) 2019 Fabrice Salvaire
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
####################################################################################################

__all__ = [
    'lorem_ipsum_20',
]

####################################################################################################

lorem_ipsum_20 = '''
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ullamcorper erat magna. Ut tempor aliquam arcu, sit amet dignissim orci vestibulum ut. Cras eget turpis nibh. Morbi a elementum nulla. Nunc at nisi nec tellus fringilla mattis ut eu metus. Cras cursus turpis non aliquam accumsan. Aenean at tortor eget mauris rutrum aliquam. Nullam volutpat libero vitae ligula sagittis pulvinar. Sed eu ex nec lorem sodales pulvinar. In placerat luctus tellus.

Maecenas in lacus ex. Sed at lacus sodales, interdum orci eu, pharetra sem. Morbi tincidunt sollicitudin nisl, in placerat mauris efficitur et. Duis tellus elit, vehicula in posuere iaculis, sodales ac lectus. Praesent dictum dapibus augue ac molestie. Donec porttitor mattis scelerisque. Proin eros ligula, aliquet a ante ac, semper volutpat ex. Integer suscipit blandit tristique. Pellentesque eget mauris at eros congue sagittis ut id massa. Suspendisse nec ante felis. Vestibulum et quam arcu. Morbi condimentum risus id venenatis venenatis. Quisque sit amet tristique sapien. Nullam placerat tortor eu scelerisque convallis.

Vivamus cursus nisl at dignissim fringilla. Fusce posuere facilisis turpis lacinia scelerisque. Aenean ornare dictum arcu, ac eleifend enim ultricies id. Vivamus eu massa vel sem volutpat mattis. Proin in odio non dui auctor convallis. Nunc mollis varius consectetur. Etiam sodales luctus nibh, vel tempus leo varius in. Maecenas ex ante, condimentum in felis eu, feugiat elementum mi. Pellentesque vel purus mi. Maecenas lobortis blandit consectetur. Proin tristique tellus risus, at malesuada mauris tristique id.

Donec venenatis pulvinar enim sed tincidunt. Integer vel erat at augue elementum lacinia. Quisque consequat sed tortor at venenatis. Nam molestie aliquet est, vel fringilla diam bibendum a. Vestibulum sed tincidunt elit, dictum efficitur risus. Phasellus ut tincidunt lorem. Vivamus nec elit a odio fringilla ultricies. Sed suscipit finibus risus vel efficitur. Praesent vitae mauris porttitor, finibus ipsum vel, scelerisque ex. Sed pellentesque efficitur turpis, et vehicula erat dictum tempus. Proin pulvinar mi facilisis urna hendrerit, eu placerat nisi iaculis.

Maecenas tempor porttitor libero quis auctor. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Integer nisi nisi, ultricies sed dui ut, sagittis rhoncus enim. Maecenas neque tortor, pellentesque ut sem ac, dictum aliquam libero. Aenean dignissim enim sem, sed hendrerit metus eleifend aliquet. Quisque lacinia enim id urna tempus iaculis. Fusce non congue enim. Aliquam erat volutpat. Morbi facilisis diam ut dictum rhoncus. Aliquam nibh libero, laoreet sit amet dui ac, tempus pretium erat. Nullam nisl est, tincidunt et libero ac, scelerisque tempus metus. Nullam varius, dolor a auctor laoreet, urna tellus tincidunt quam, ac porta elit lectus eu mauris. Phasellus a dui massa. Suspendisse pulvinar ex ipsum, tristique ultrices nisl malesuada ac. Fusce vehicula nisi eu magna sollicitudin tincidunt. Suspendisse potenti.

Quisque ut libero ornare, sollicitudin magna et, viverra purus. Praesent mauris elit, rutrum at felis eu, placerat sagittis felis. Mauris finibus dignissim molestie. Donec tincidunt massa quis lacus pulvinar, sed venenatis mauris bibendum. Pellentesque in facilisis velit. Curabitur non orci sit amet sem ultricies imperdiet sed ac justo. Integer eget congue eros, quis fermentum libero. Curabitur eget nulla justo. Integer consectetur ipsum sit amet luctus condimentum. Maecenas condimentum turpis metus, quis imperdiet magna lacinia ac. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla sit amet feugiat neque, at eleifend erat.

Morbi sit amet magna nec risus malesuada faucibus. Ut ut massa id velit tempus sodales nec eu tortor. Donec tempus nisl vitae interdum suscipit. Donec vitae nunc eros. Nam tincidunt magna augue, nec viverra magna iaculis vitae. Maecenas cursus dictum sollicitudin. Phasellus tristique porta posuere. Pellentesque eu ipsum nisi. Pellentesque vestibulum volutpat leo placerat sollicitudin. Integer dictum neque ut mi posuere, et maximus est porttitor. Maecenas non nunc ut tortor mollis tristique nec eu lacus. Nam at maximus felis, in facilisis nunc. Vestibulum risus mauris, fermentum sit amet malesuada in, aliquet ac lectus. Nullam et lobortis arcu. Integer pharetra congue erat eu volutpat.

Integer erat tortor, eleifend in dignissim quis, tristique sed justo. Pellentesque scelerisque lacus eget velit tincidunt ultrices. Sed laoreet scelerisque metus in condimentum. Donec ipsum urna, tristique at viverra ut, pellentesque consectetur elit. Ut auctor fringilla iaculis. Ut id ex nulla. Etiam neque nisl, eleifend quis congue et, mattis ac ante. Curabitur vehicula ut lacus nec lobortis. Phasellus consectetur neque quis nulla vestibulum sagittis quis non nunc. Nunc nec velit faucibus, tincidunt nulla luctus, aliquam dolor. Aliquam sed vestibulum turpis, sed tempus neque. Pellentesque aliquet eros quis diam condimentum volutpat. Cras mattis velit a sodales cursus. Suspendisse fringilla, sapien at gravida vehicula, nisl lorem tincidunt tellus, sed cursus lorem mauris sed est. Vivamus efficitur ex ac rutrum egestas.

Phasellus porttitor lobortis magna vel ullamcorper. Morbi placerat, tellus mattis interdum ultrices, sem orci convallis ex, id euismod nisi leo sit amet metus. Etiam eu metus odio. Mauris nunc est, molestie id bibendum venenatis, molestie sit amet mauris. Nulla sollicitudin erat ut semper dapibus. Proin dignissim lacus mollis, ullamcorper ipsum vel, accumsan mi. Maecenas eget sodales ex. Vestibulum eu nibh id neque ornare sodales congue id nulla. Etiam dui nulla, venenatis sit amet leo quis, commodo eleifend nisl.

Quisque congue rutrum massa, in gravida sapien euismod nec. Nullam hendrerit eros non semper accumsan. Donec eget metus mauris. Suspendisse nec quam pulvinar, finibus augue in, consectetur tortor. Nullam tempor, massa malesuada laoreet molestie, ipsum mi iaculis diam, nec venenatis lacus nibh eu nisl. Praesent aliquet maximus aliquet. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Pellentesque nulla ex, sagittis pulvinar felis et, ultricies hendrerit eros. Nam lacinia, diam sed facilisis tincidunt, sem arcu egestas nulla, non congue nulla sem nec ipsum. Cras porttitor non eros in commodo. Proin tempor eros vitae nunc molestie, et imperdiet leo consectetur. Sed vitae tempor tortor, sit amet accumsan mauris. Proin congue neque consectetur, volutpat leo quis, convallis ipsum. Quisque tristique pellentesque maximus.

Morbi mauris ex, tristique vitae suscipit at, varius sit amet turpis. Praesent non tortor vel enim gravida dapibus nec hendrerit nisl. Etiam eu purus ultricies, imperdiet arcu id, congue enim. Donec blandit pulvinar metus, id porttitor enim viverra in. Ut interdum feugiat ligula, vitae dapibus mi feugiat ut. Phasellus et magna est. Etiam fringilla, neque a semper pharetra, elit elit convallis nibh, non efficitur ante metus eu sem. Curabitur maximus nisl commodo, sodales elit at, fermentum ipsum. Nulla condimentum ex iaculis, eleifend dui non, aliquam elit. Nam accumsan velit in velit ultricies dignissim. Sed placerat magna vel laoreet dignissim. In hac habitasse platea dictumst. Morbi nec tempor ante. Quisque in velit est. Quisque non euismod sapien.

Mauris pellentesque ligula ut consectetur volutpat. Cras in nunc porttitor, imperdiet turpis vel, efficitur risus. Sed sagittis purus quam, at blandit odio interdum a. Nulla facilisi. Ut et consequat diam, consectetur vulputate felis. Donec ac malesuada velit, nec posuere diam. In accumsan tincidunt nibh, ac scelerisque ligula mattis sodales. Morbi lacinia congue volutpat. Nulla sit amet rhoncus justo. Nam ligula enim, faucibus non dapibus quis, dapibus pharetra arcu. Quisque mi libero, lacinia non nibh cursus, finibus cursus nunc. Curabitur rhoncus fermentum augue et dictum.

Etiam nibh mi, dictum at condimentum at, rhoncus faucibus justo. Fusce auctor nec leo nec volutpat. Morbi sagittis sodales convallis. Phasellus nisl urna, faucibus ac magna vestibulum, vulputate sollicitudin lectus. Praesent suscipit efficitur urna, commodo porta diam accumsan quis. Praesent vel dui quis ipsum cursus bibendum. In nisl erat, ullamcorper a justo elementum, lacinia suscipit magna. Quisque dapibus mi non leo euismod maximus. Suspendisse pretium urna felis, fringilla interdum urna fringilla viverra. Curabitur et odio id mi rutrum accumsan. Vestibulum a accumsan sem. Aliquam eget hendrerit leo, quis finibus nunc. Nam dapibus ex ex, vel vehicula dui pulvinar eu.

Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus vel vestibulum orci. Phasellus tortor massa, mollis eget felis id, aliquam ullamcorper magna. Praesent congue venenatis interdum. Phasellus venenatis urna interdum iaculis facilisis. Quisque gravida pellentesque dignissim. Fusce varius massa a suscipit lacinia. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Sed congue hendrerit arcu ac lacinia. Pellentesque egestas faucibus purus, a malesuada sem tempor porta. Nam augue nulla, facilisis a aliquet sit amet, rutrum ac sapien.

Mauris a auctor nunc. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nulla vel est lacus. Donec diam diam, molestie quis eros eu, interdum tempus leo. Sed fringilla tellus nec odio luctus tristique. Morbi ut purus nec nisl dictum vulputate. Donec rutrum vehicula nisl quis dignissim. Maecenas ac eros in sapien molestie auctor sit amet a felis. Nam eget purus consequat, pharetra massa a, tincidunt libero.

Phasellus vitae ultrices augue. Mauris in nisl eget urna euismod tristique pharetra et risus. Nulla lectus metus, hendrerit eu viverra nec, porttitor non nunc. Integer tempor massa purus, vitae posuere purus interdum et. Nam suscipit urna tortor, eget vehicula lectus sodales posuere. In rhoncus enim id pellentesque convallis. Sed vulputate augue quis ligula tristique, ac sagittis nibh ultrices. Suspendisse vitae tortor nec purus finibus rutrum condimentum pulvinar felis. Morbi tristique erat in odio efficitur pulvinar. Nullam congue fringilla sapien, sodales sodales tellus. Aliquam fermentum dui sit amet erat rhoncus vestibulum. Sed dignissim, metus nec laoreet dapibus, sem erat consequat orci, id cursus libero velit sed lectus.

Aliquam vel laoreet sapien. Ut ullamcorper rhoncus neque consectetur ultricies. Proin tortor lorem, blandit eget nunc ut, pharetra blandit nibh. Vestibulum a turpis sed est facilisis mollis. Donec sit amet justo porttitor, semper ipsum at, lobortis purus. Vivamus tristique velit quis leo dignissim consequat id porttitor felis. Nam ac quam sit amet quam tincidunt volutpat. Vestibulum vitae nibh id erat bibendum malesuada. Vivamus tempor condimentum dolor. Integer in lorem luctus, hendrerit leo sed, rhoncus mauris. Quisque id leo eget purus lobortis congue vel congue lacus. Nullam consequat tellus velit, nec elementum mauris consequat in. Etiam a augue felis.

Ut nec quam eget sem vulputate efficitur. Maecenas id nisl sed nunc maximus imperdiet. Aenean ut leo quis arcu ultrices condimentum. Quisque sagittis metus at quam molestie, vel vestibulum eros tristique. Mauris ut tellus quis metus rhoncus accumsan eget non risus. Aliquam a neque venenatis, posuere tellus ut, sodales sem. Nulla ultricies scelerisque nunc, sit amet congue lorem bibendum in.

Nunc iaculis fermentum imperdiet. Cras lobortis auctor tellus, ut vehicula dui. Interdum et malesuada fames ac ante ipsum primis in faucibus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Vestibulum tellus tortor, mollis quis eleifend cursus, cursus vitae erat. Nam facilisis viverra pretium. Nam quis rhoncus tortor. Vestibulum suscipit tortor at facilisis efficitur. Phasellus ut purus vehicula, interdum nulla et, malesuada arcu. Duis eget magna dictum, rhoncus nisi a, interdum tellus. Nulla et massa eu sapien porta viverra id quis leo. Ut faucibus nunc vitae dapibus imperdiet.

Integer quis augue sit amet tortor tempus tempus. Maecenas lacinia convallis accumsan. Vestibulum auctor eleifend dignissim. Curabitur porttitor velit ut tortor auctor molestie. Nam eu nisl eros. Vestibulum aliquam diam nulla, nec vestibulum ipsum pellentesque non. Pellentesque vel auctor mi. Fusce vehicula metus eu libero malesuada, id dignissim ipsum semper.
'''
