#! /usr/bin/bash

find BookBrowser -name "flycheck*.py" -exec rm {} \;
find BookBrowser -name "parsetab.py" -exec rm {} \;

api=doc/sphinx/source/api
rm -rf ${api}

echo
echo Generate RST API files
pyterate-rst-api BookBrowser

echo
echo Run Sphinx
pushd doc/sphinx/
./make-html #--clean
popd
