#! /bin/bash

# see https://material.io/icons/

PATH=$PWD/scripts:$PATH

copy-icon action alarm
copy-icon action hourglass_empty
copy-icon action settings_overscan
copy-icon action swap_vert
copy-icon action view_module
copy-icon action zoom_in
copy-icon action zoom_out
copy-icon hardware scanner
copy-icon file folder
copy-icon image grid_off
copy-icon image grid_on
copy-icon image image
copy-icon image view_comfy
copy-icon navigation arrow_back
copy-icon navigation arrow_forward
copy-icon navigation chevron_left
copy-icon navigation chevron_right
copy-icon navigation first_page
copy-icon navigation last_page
copy-icon navigation refresh
