#! /bin/bash

# see https://material.io/icons/

PATH=$PWD/scripts:$PATH

copy-icon action alarm
copy-icon action build
copy-icon action delete
copy-icon action done
copy-icon action find_in_page
copy-icon action grade
copy-icon action help
copy-icon action home
copy-icon action hourglass_empty
copy-icon action info
copy-icon action list
copy-icon action settings
copy-icon action settings_overscan
copy-icon action swap_vert
copy-icon action view_module
copy-icon action zoom_in
copy-icon action zoom_out
copy-icon alert error
copy-icon alert warning
copy-icon content add_circle
copy-icon content create
copy-icon content font_download
copy-icon content remove_circle
copy-icon content save
copy-icon editor mode_edit
copy-icon file folder
copy-icon hardware scanner
copy-icon image crop
copy-icon image grid_off
copy-icon image grid_on
copy-icon image image
copy-icon image view_comfy
copy-icon navigation arrow_back
copy-icon navigation arrow_forward
copy-icon navigation chevron_left
copy-icon navigation chevron_right
copy-icon navigation first_page
copy-icon navigation last_page
copy-icon navigation refresh
